spring:
  kafka:
    consumer:
      bootstrap-servers: 172.23.238.163:9092
    bootstrap-servers: 172.23.238.163:9092
producer:
  location:
    topic: outputToIndexer
    
consumer:
  location:
    topic: UserLocation