version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    depends_on:
      config-service:
        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-eureka-service
    hostname: localhost
    ports:
      - 9090:9090
    healthcheck:
      test: "exit 0"

  config-service:
    build: config-service/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8891:8891
    healthcheck:
      test: "exit 0"

  api-gateway:
    build: zuul-apigateway/
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
#      user-service:
#        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-zuul-service
    hostname: localhost
    ports:
      - 8092:8092
    healthcheck:
      test: "exit 0"


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: "host"
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CREATE_TOPICS: "Location:1:1, Certificates:1:1, Academies:1:1, PersonalInfo:1:1, Experience:1:1, Projects:1:1, Skills:1:1"
    network_mode: "host"
    hostname: localhost
    depends_on:
      - zookeeper
    restart: always
    healthcheck:
      test: "exit 0"

 user-service:
   build: user-service/
   image: demo-user-service
   restart: always
   network_mode: "host"
   hostname: localhost
   ports:
     - 8081:8081
   depends_on:
     - config-service
     - eureka-server
   healthcheck:
     test: "exit 0"

  personal-service:
    build: personalinformation-microservice/ 
    image: personal-service
    ports: 
      - 8087:8087
    restart: always
    network_mode: "host"
    hostname: localhost
    healthcheck:
      test: "exit 0"

  location-service:
    build: location-microservice/
    image: loca-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8086:8086
    healthcheck:
      test: "exit 0"

  experience-service:
    build: experience-microservice/
    image: experience-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8083:8083
    healthcheck:
      test: "exit 0"

  training-service: 
    build: training-microservice/
    image: training-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8084:8084
    healthcheck:
      test: "exit 0"

  project-service:
    build: project-microservice/
    image: project-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8088:8088
    healthcheck:
      test: "exit 0"

  skill-service:
    build: skill-microservice/
    image: skill-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8089:8089
    healthcheck:
      test: "exit 0"

  qualification-service:
    build: qualification-microservice
    image: qualification-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8085:8085
    healthcheck:
      test: "exit 0"
    
