spring:
  kafka:
    bootstrap-servers: localhost:9092
    
app:
  topic:
     training: Certificates
     
listener:
    topic:
      name: training

indexer:
    topic:
       name: TrainingIndexer  

server: 
  port: 8084   
    
  
