<<<<<<< HEAD
spring:
  kafka:
    bootstrap-servers: localhost:9092
    
app:
  topic:
     training: Certificates
     
listener:
    topic:
      name: training

indexer:
    topic:
       name: TrainingIndexer  

server: 
  port: 8084   
    
  
=======
>>>>>>> ac82e351da1f154eeb53f2de1e6733e8c84f777d
